security:
    encoders:
        Nekland\NekoWiki\Entity\User\User:
            algorithm:           sha512
            encode_as_base64:    true
            iterations:          103

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class: Nekland\NekoWiki\Entity\User\User
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path:          login_check
                login_path:          login
                default_target_path: profile
            logout:
                path:   logout
                target: homepage
            anonymous: ~

    access_control:
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
