parameters:
    neko_wiki.searcher.class: App\Search\RepositorySearch

services:
    neko_wiki.searcher:
        class: %neko_wiki.searcher.class%
        arguments: [ @neko_wiki.repository.page, @neko_wiki.language.manager ]


#        class: App\Search\ElasticSearch
#        arguments: [ @fos_elastica.finder.neko_wiki.page, @neko_wiki.repository.page ]



    neko_wiki.search.elasticsearch.register_page_translation:
        class: App\Search\ElasticSearch\Listeners\RegisterPageTranslation
        tags:
            - { name: doctrine.event_subscriber }
